apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-info-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: pod-info
  template:
    metadata:
      labels:
        app: pod-info
    spec:
      serviceAccountName: pod-info-service-account
      containers:
        - name: pod-info
          image: ghcr.io/corneilleedi/pod-info:2.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-info-service-account

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-info-cluster-role
rules:
  - apiGroups: [ "" ]
    resources: [ "pods" ]
    verbs: [ "get", "list" ]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-info-cluster-role-binding
subjects:
  - kind: ServiceAccount
    name: pod-info-service-account
    namespace: default
roleRef:
  kind: ClusterRole
  name: pod-info-cluster-role
  apiGroup: rbac.authorization.k8s.io